# These are supported funding model platforms

# github: [user1, user2]
# patreon: user
# open_collective: project
# ko_fi: user
# tidelift: platform-name/package-name
# lera: user
# liberapay: user
# issuehunt: username
# otechie: username
# custom: ["https://boosty.to/your_username_here"] # Placeholder or comment out if none yet
custom: []
